// // This file is automatically generated. Do not edit it directly.
// import { createClient } from '@supabase/supabase-js';
// import type { Database } from './types';

// const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
// const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// // Import the supabase client like this:
// // import { supabase } from "@/integrations/supabase/client";

// export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
//   auth: {
//     storage: localStorage,
//     persistSession: true,
//     autoRefreshToken: true,
//   }
// });

import { createClient } from "@supabase/supabase-js";

// Ensure environment variables exist and are not empty
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!supabaseUrl) {
  throw new Error("❌ Missing VITE_SUPABASE_URL in .env");
}

if (!supabaseAnonKey) {
  throw new Error("❌ Missing VITE_SUPABASE_PUBLISHABLE_KEY in .env");
}

// Basic format validation to give a clearer error if the environment contains
// an invalid Supabase URL; this avoids confusing errors like "Failed to fetch".
try {
  new URL(supabaseUrl);
} catch (err) {
  throw new Error("❌ VITE_SUPABASE_URL does not appear to be a valid URL");
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
